export const KYC_DATA_LOADING_STARTS = 'KYC_DATA_LOADING_STARTS';
export const KYC_DATA_LOADING_ENDS = 'KYC_DATA_LOADING_ENDS';
export const GET_KYC_DATA = 'GET_KYC_DATA';
export const GET_KYC_SINGLE_DATA = "GET_KYC_SINGLE_DATA";

export const LOAN_DATA_LOADING_STARTS = 'LOAN_DATA_LOADING_STARTS';
export const LOAN_DATA_LOADING_ENDS = 'LOAN_DATA_LOADING_ENDS';
export const GET_LOAN_DATA = 'GET_LOAN_DATA';
export const LOAN_DATA_ERROR = 'LOAN_DATA_ERROR';
export const CLEAR_LOAN_DATA_ERROR = 'CLEAR_LOAN_DATA_ERROR';
export const GET_LOAN_SINGLE_DATA = "GET_LOAN_SINGLE_DATA";

export const GET_APPLICATION_ERROR = 'GET_APPLICATION_ERROR';
export const CLEAR_APPLICATION_ERROR = 'CLEAR_APPLICATION_ERROR';

export const REDIRECT_TO = "REDIRECT_TO"