export const ADMIN_KYC_DATA_LOADING_STARTS = 'ADMIN_KYC_DATA_LOADING_STARTS';
export const ADMIN_KYC_DATA_LOADING_ENDS = 'ADMIN_KYC_DATA_LOADING_ENDS';
export const ADMIN_GET_KYC_DATA = 'ADMIN_GET_KYC_DATA';
export const ADMIN_GET_KYC_SINGLE_DATA = "ADMIN_GET_KYC_SINGLE_DATA";

export const ADMIN_LOAN_DATA_LOADING_STARTS = 'ADMIN_LOAN_DATA_LOADING_STARTS';
export const ADMIN_LOAN_DATA_LOADING_ENDS = 'LOAN_DATA_LOADING_ENDS';
export const ADMIN_GET_LOAN_DATA = 'GET_LOAN_DATA';
export const LOAN_DATA_ERROR = 'LOAN_DATA_ERROR';
export const CLEAR_ADMIN_LOAN_DATA_ERROR = 'CLEAR_ADMIN_LOAN_DATA_ERROR';
export const GET_ADMIN_LOAN_SINGLE_DATA = "GET_ADMIN_LOAN_SINGLE_DATA";

export const GET_APPLICATION_ERROR = 'GET_APPLICATION_ERROR';
export const CLEAR_APPLICATION_ERROR = 'CLEAR_APPLICATION_ERROR';

export const REDIRECT_TO = "REDIRECT_TO"