export const LOAN_DATA_LOADING_STARTS = 'LOAN_DATA_LOADING_STARTS';
export const LOAN_DATA_LOADING_ENDS = 'LOAN_DATA_LOADING_ENDS';
export const GET_LOAN_DATA = 'GET_LOAN_ATA';
export const LOAN_DATA_ERROR = 'LOAN_DATA_ERROR';
export const CLEAR_LOAN_DATA_ERROR = 'CLEAR_LOAN_DATA_ERROR';
export const GET_LOAN_DATA_ERROR = 'GET_LOAN_DATA_ERROR';
export const GET_A_LOAN_DATA = 'GET_A_LOAN_DATA';

export const VIEW_SINGLE_LOAN_LOADING_STARTS = "VIEW_SINGLE_LOAN_LOADING_STARTS";
export const VIEW_SINGLE_LOAN_LOADING_ENDS = "VIEW_SINGLE_LOAN_LOADING_ENDS";

export const CRUD_OPERATIONS_STARTS = "CRUD_OPERATIONS_STARTS";
export const CRUD_OPERATIONS_ENDS = "CRUD_OPERATIONS_ENDS";