export const DASHBOARD_DATA_LOADING_STARTS = "DASHBOARD_DATA_LOADING_STARTS"
export const DASHBOARD_DATA_LOADING_ENDS = "DASHBOARD_DATA_LOADING_ENDS"
export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA"