export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CHECK_USER_ROLE = "CHECK_USER_ROLE";
export const ROLE_LOADING_STARTS = "ROLE_LOADING_STARTS";
export const ROLE_LOADING_ENDS = "ROLE_LOADING_ENDS";
export const AUTH_LOADING_STARTS = "AUTH_LOADING_STARTS";
export const AUTH_LOADING_ENDS = "AUTH_LOADING_ENDS";
export const REDIRECT_TO = "REDIRECT_TO";
export const GET_LOGGED_IN_USER_DETAILS = GET_LOGGED_IN_USER_DETAILS;
