export const SHOW_NETWORK_RESPONSE = "SHOW_NETWORK_RESPONSE";
export const CLEAR_NETWORK_RESPONSE = "CLEAR_NETWORK_RESPONSE";
export const REDIRECT_TO = "REDIRECT_TO";
export const FETCH_ERROR = "FETCH_ERROR";