export const ADMIN_DASHBOARD_DATA_LOADING_STARTS = "ADMIN_DASHBOARD_DATA_LOADING_STARTS";
export const ADMIN_DASHBOARD_DATA_LOADING_ENDS = "ADMIN_DASHBOARD_DATA_LOADING_ENDS";
export const GET_ADMIN_DASHBOARD_DATA = "GET_ADMIN_DASHBOARD_DATA";

export const GET_ALL_USERS_COUNT = "GET_ALL_USERS_COUNT";

export const GET_LAST_FIVE_USERS = "GET_LAST_FIVE_USERS"